name: Integration Test Find&Replace Action
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find&Replace href="any_url_path.html"->href="any_url_path"
        id: selftest
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "**/*.html"
          find: '(href="[^\.]*).html'
          replace: "$1"
          regex: true
#      - name: Check outputs and modified files
#        run: |
#          test "${{ steps.selftest.outputs.modifiedFiles }}" == "1"
#          grep "Hello there" tests/hello.txt

      - name: Print OutputsValue
        run: echo "${{ steps.selftest.outputs.value }}"
      - name: Print ModifiedFiles
        if: ${{ steps.selftest.outputs.modifiedFiles }} > 0
        run: echo "${{ steps.selftest.outputs.modifiedFiles }}"

      - name: Commit files
        if: ${{ steps.selftest.outputs.modifiedFiles }} > 0
        run: |
         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions[bot]"
         git commit -m 'Replace href="any_url_path.html"->href="any_url_path"' -a          
      - name: Push changes
        if: ${{ steps.selftest.outputs.modifiedFiles }} != 0
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
